---
- name: restart flannel
  service: name=flannel state=restarted
  notify:
    - stop docker
    - delete docker0
    - start docker

- name: stop docker
  service: name=docker state=stopped
  when: inventory_hostname in groups['node']

- name: delete docker0
  command: ip link delete docker0
  ignore_errors: yes
  when: inventory_hostname in groups['node']

- name: start docker
  service: name=docker state=started
  when: inventory_hostname in groups['node']
