---
- name: install etcd
  apt: name=etcd update_cache=yes state=present cache_valid_time=3600

- name: create etcd configuration
  template: src=etc/init/etcd.conf.j2 dest=/etc/init/etcd.conf
  notify: restart etcd

- name: start etcd
  service: name=etcd state=started

- name: install kubernetes master
  apt: name=kubernetes-master state=present cache_valid_time=3600

- name: start kube-apiserver
  service: name=kube-apiserver state=started

- name: start kube-controller-manager
  service: name=kube-controller-manager state=started

- name: start kube-scheduler
  service: name=kube-scheduler state=started
