---

- name: k8s master
  hosts: master

  roles:
    - common
    - master
    - flannel

- name: k8s node
  hosts: node

  roles:
    - common
    - flannel
    - node

- name: configure flannel
  hosts: master.0

  tasks:
    - name: check for configuration
      register: key_check
      changed_when: False
      command: >
        etcdctl get /coreos.com/network/config > /dev/null
    - name: set configuration
      when: key_check | failed
      command: >
        etcdctl set /coreos.com/network/config '{ "Network": "172.18.0.0/16", "Backend": { "Type": "udp" } }'

