---

- name: k8s common
  hosts: master, node
  roles:
    - common

- name: k8s master
  hosts: master
  tags:
    - master
  roles:
    - master

- name: k8s node
  hosts: node
  tags:
    - node
  roles:
    - node

- name: install flannel
  hosts: master, node
  roles:
    - flannel

- name: configure flannel
  hosts: master.0
  tasks:
    - name: check for configuration
      register: key_check
      changed_when: false
      ignore_errors: true
      command: >
        etcdctl get /coreos.com/network/config > /dev/null
    - name: set configuration
      when: key_check | failed
      command: >
        etcdctl set /coreos.com/network/config '{ "Network": "172.18.0.0/16", "Backend": { "Type": "udp" } }'

